name: Me Botto

on:
  # schedule:
  #   # every 10 minutes the job will run
  #   - cron: "*/10 * * * *"
  push:
    branches:
      - master
  repository_dispatch:
    types: [my-event]
jobs:
  run-bot:
    runs-on: ubuntu-18.04
    # timeout-minutes: 9  

    steps:
    - uses: actions/checkout@v2
      with:
        ref: bot
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    
    - name: Install OS dependencies
      run: |
          sudo apt-get update
          sudo apt-get install build-essential libpoppler-cpp-dev ghostscript pkg-config locales
    
    - name: Install Python dependencies
      run: pip install --upgrade pip && pip install wheel && pip install -r requirements.txt
    
    - name: Start Bot
      run: |
        python start_bot.py
      env:
          LANG: "en_US.UTF-8"
          COVID_BOT_TOKEN: ${{ secrets.COVID_BOT_TOKEN }}
          VISIONAPI_TOKEN: ${{ secrets.VISIONAPI_TOKEN }}
          UPDATE_ID: ${{ github.event.client_payload.update_id }}
    
    - name: Repository Dispatch
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.SRM_TOKEN}}
        script: |
          const fs = require('fs');
          update_id = fs.readFileSync('/tmp/update_id', 'utf8');
          console.log("This is the last update_id: "+update_id);
          await github.repos.createDispatchEvent({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  event_type: "my-event",
                  client_payload: { greeting: "hello", update_id: update_id }
                });
